### ISSUE TITLE
utf-8 bug?

### ISSUE THREAD

**Issue by YoniChechik** [jupyterhub/binderhub#926] opened 2019-08-13 21:29 UTC
this is my error (after trying to fix it myself):

Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker_t69z433'...
HEAD is now at c112515 utf-8 bugfix
Error
during build: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
this is my github
https://github.com/YoniChechik/computer_vision_course

what am I doing wrong?

**Comment by betatim** [comment] 2019-08-14 05:02
Duplicate of https://github.com/jupyterhub/mybinder.org-deploy/issues/1125 (please don't post in more than one place)

**Closed by betatim** 2019-08-14 05:02 UTC
