### ISSUE TITLE
"Stream disconnected" when building a new repo

### ISSUE THREAD

**Issue by betatim** [jupyterhub/binderhub#140] opened 2017-09-29 06:59 UTC
Building one of my repos seems to consistently lead to "stream disconnected" errors. If you hit launch again or simply refresh the page it will eventually go to "launching". Maybe just a problem in the displaying of information?

![pasted image at 2017_09_28 04_50 pm](https://user-images.githubusercontent.com/1448859/31004361-5465fafa-a4f4-11e7-8d77-4a39d7c2db5c.png)

**Comment by minrk** [comment] 2017-09-29 13:55
This message will occur if the event stream is closed without sending a proper error. I believe that most such events will be fixed by #135 reporting errors on the event stream properly, rather than trying to send a normal HTTP error after the event stream is hooked up.

I was able to build this repo on the beta an hour or so ago, so it may have been a transient issue.

**Comment by betatim** [comment] 2017-09-29 15:10
The confusing thing is that I saw this error but as soon as you hit refresh (maybe wait briefly first) you get forwarded to the launched container. So building worked but somehow the UI get's stuck?

**Comment by minrk** [comment] 2017-10-02 16:24
Yup, probably a bug in the event stream code (not sure which side).

**Closed** 2017-10-06 19:12 UTC
Labels: bug, needs: testing

**Comment by minrk** [comment] 2017-10-06 19:13
This was not a bug per se in the event stream code, but nginx dropping the event stream connection when it's idle for 60 seconds. This is fixed by #172.

https://staging.mybinder.org/v2/gh/minrk/junk/sleep-and-die demonstrates the issue.

**Comment by yuvipanda** [comment] 2017-10-06 21:24
tyvm, @minrk!
