### ISSUE TITLE
Make mybinder.org landing page clearer for "users"

### ISSUE THREAD

**Issue by marius311** [jupyterhub/binderhub#364] opened 2017-12-19 19:40 UTC
I've added a Binder badge to my Github repo and advertised it as a "one-click way to get a running example notebook for my code". However, when a user clicks the badge, they're taken to a page that looks like this (I know everyone knows what it looks like, but just for definiteness):

![image](https://user-images.githubusercontent.com/1510968/34175153-b8a79162-e4fb-11e7-81fe-c4794bc53442.png)

For a user that may not know what Binder is, and indeed I don't expect them all to, I would argue this is quite confusing and a lot of information overload. Really they just need to be told "hold tight, the notebook is going to appear". Instead, they are probably asking themselves "do I need to fill in these text fields?" or "do I need to click that launch button?"

This current interface is certainly great for us notebook "providers", but for the "users" it'd be great if instead we could have a simpler UI that was something like a single line of text saying in some form "just wait" and one big progress bar.

**Comment by yuvipanda** [comment] 2017-12-19 20:43
We totally agree! That should be the experience for people coming in.

**Comment by choldgraf** [comment] 2017-12-19 23:05
totally agree, this is being discussed in #350, #196 and #271

actually, I'm gonna close this as a dupe of #271, though I totally agree w/ @marius311 that this is a very important issue to tackle soon.

**Closed by choldgraf** 2017-12-19 23:05 UTC
