### ISSUE TITLE
notebooks are read only

### ISSUE THREAD

**Issue by cekees** [jupyterhub/binderhub#71] opened 2017-07-04 12:18 UTC
When I open notebooks I can run them, but they can't write to disk and display a "read-only" icon in the right hand corner of the notebook.
https://beta.mybinder.org/v2/gh/erdc-cm/oxford2017/master

**Comment by choldgraf** [comment] 2017-07-04 17:17
This has been a problem that pops up periodically. I wonder if it's a Python 2 issue. @cekees can you try this out with a python 3 environment or does your code depend on python 2?

**Comment by minrk** [comment] 2017-07-19 14:35
My guess is it's the USER when the COPY command runs not being the same as the builder. We need to do some verification that $HOME files have the right permissions in the builders.

**Comment by choldgraf** [comment] 2017-08-15 19:09
Is this resolved now with newer additions to binderhub / jupyterhub?

**Comment by willingc** [comment] 2017-08-16 13:32
@choldgraf What's the URL of the current beta instance of Binder? 

I can drop the link: https://github.com/erdc-cm/oxford2017.git into it and test.

**Comment by minrk** [comment] 2017-08-16 14:19
https://beta.mybinder.org

**Comment by cekees** [comment] 2017-08-19 12:36
Thanks @willingc, I checked again and the situation seems the same. I can open new python 2 or 3 notebooks and save them, but the notebooks in the binder can't be saved or copied. I don't have any notebooks in that binder that are Python3 so I can't check that easily @choldgraf.

**Comment by choldgraf** [comment] 2017-11-28 23:27
I think that @minrk 's comment is probably correct...I bet that permissions aren't correct for the notebooks. 

@cekees can you edit your Dockerfile per these instructions below and say if this cleans up your problem?

https://mybinder.readthedocs.io/en/latest/dockerfile.html#preparing-your-dockerfile

**Comment by choldgraf** [comment] 2018-01-12 19:56
Is this issue now resolved? I think it's been fixed w/ repo2docker changes

**Comment by betatim** [comment] 2018-01-13 09:47
Closing this for now. Just tried to launch the [binder](https://beta.mybinder.org/v2/gh/erdc-cm/oxford2017/master) and it just sits there waiting for a server to launch. The repo uses a `Dockerfile` which inherits from a different `Dockerfile` so right now I think the problem is somewhere in that setup. My guess notebooks are being copied as a user that is different from the one used when executing them. I can't recall other recent reports about a similar problem. @cekees if you get stuck again do re-open this.

**Closed by betatim** 2018-01-13 09:47 UTC
Labels: bug

**Comment by cekees** [comment] 2018-01-13 14:55
Thanks @betatim @choldgraf and @minrk .  I've been swamped with other projects but will try to update my Dockerfiles with the fix in the next few weeks.
