### ISSUE TITLE
`No space left on device` error when trying to build from repository

### ISSUE THREAD

**Issue by jwood803** [jupyterhub/binderhub#105] opened 2017-09-11 16:22 UTC
Trying to build [this repository](https://github.com/Wintellect/DataScienceExamples) of notebooks, but I always get a `No space left on device` error when it tries to build the Docker image.

**Comment by choldgraf** [comment] 2017-09-11 16:26
hmm - I just built w/ the link for your repository and it worked for me. Though it didn't actually build a new image, just took me to a pre-built image.

This feels to me like it's probably our disk filling up in the google cloud deployment (we've got the resources scaled back a bit since it's still in beta). Can you share a binder link that recreates the problem?

**Comment by jwood803** [comment] 2017-09-11 16:36
Hopefully, this [link](http://mybinder.org/status/wintellect/datascienceexamples/) works for you to see what I'm seeing :)

I wonder, since I have CSVs in the repository, that it may be too big for the binder to build.

**Comment by choldgraf** [comment] 2017-09-11 16:41
ah hah - can you try this with the `beta` binder link? It's a totally new deployment running on totally separate resources, and will be the future infrastructure powering binder:

see:

beta.mybinder.org

and the link structure would be:

beta.mybinder.org/v2/gh/Wintellect/DataScienceExamples/master

**Comment by jwood803** [comment] 2017-09-11 16:50
Looks like it [builds](https://hub.binder-beta.omgwtf.in/user/806d241f-4398-4f61-891e-6ac0cd0ee336/https://github.com/notebooks/Wintellect/DataScienceExamples/blob/master/Sales%20Data/Outlier%20Example.ipynb?), but I get a 404 error:
![image](https://user-images.githubusercontent.com/1578160/30286486-b9ba78e4-96ef-11e7-934a-9434dda78e6b.png)

**Comment by choldgraf** [comment] 2017-09-11 17:09
Hmmm, can you try this in an incognito window? Might be a bug with cookies

**Comment by jwood803** [comment] 2017-09-11 17:54
Same message when going to it in incognito.

**Comment by choldgraf** [comment] 2017-09-11 18:21
hmm, so the problem is that it's trying to send you someplace that doesn't exist within the file structure. Here's the text of your link:

`https://hub.binder-beta.omgwtf.in/user/806d241f-4398-4f61-891e-6ac0cd0ee336/https://github.com/notebooks/Wintellect/DataScienceExamples/blob/master/Sales%20Data/Outlier%20Example.ipynb?`

If you try this link:

`https://hub.binder-beta.omgwtf.in/user/806d241f-4398-4f61-891e-6ac0cd0ee336/notebooks`

does it work?

I think this is a bug w/ cookies in the browser

**Comment by jwood803** [comment] 2017-09-11 18:43
That link does work!

**Comment by choldgraf** [comment] 2017-09-16 15:04
wohoo! I'm gonna close this issue since I think it's fixed by some combination of new jupyterhub + new binderhub :-)

**Closed by choldgraf** 2017-09-16 15:04 UTC

**Comment by jwood803** [comment] 2017-09-16 15:05
Awesome! Thank you very much for the help @choldgraf!
