### ISSUE TITLE
Filepath not allowing path to subdirectory

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyterhub/binderhub#456] opened 2018-02-16 17:07 UTC
- not specifying a filepath starts with the root directory, as expected.
 - specifying a full path to a notebook behaves as expected.

However, we cannot specify a path to a subdirectory (where the notebooks would typically be).

**Comment by choldgraf** [comment] 2018-02-16 18:22
Hmmm - I just tried this URL:

https://mybinder.org/v2/gh/binder-examples/zero-to-binder/master?filepath=binder

and it **did** put me in the `binder/` folder.

@SylvainCorlay can you share the link you're using that isn't working?

**Comment by betatim** [comment] 2018-02-19 21:59
I think the problem is
```
https://mybinder.org/v2/gh/binder-examples/zero-to-binder/master?filepath=binder
```
vs
```
https://mybinder.org/v2/gh/binder-examples/zero-to-binder/master?filepath=binder/
```
(trailing slash). Should we sanitise that or just declare it illegal?

**Comment by choldgraf** [comment] 2018-02-20 01:08
IMO we should sanitize something like that as it seems like a pretty reasonable assumption that users will make

**Comment by choldgraf** [comment] 2018-02-20 01:08
@SylvainCorlay can you confirm that it works w/o the trailing slash?

**Comment by choldgraf** [comment] 2018-04-25 20:25
I think this has now been fixed, #495 is closed as well. Please re-open if there is more to be done!

**Closed by choldgraf** 2018-04-25 20:25 UTC
