### ISSUE TITLE
mpi4py not found with python3 kernel

### ISSUE THREAD

**Issue by williamfgc** [jupyterhub/binderhub#806] opened 2019-03-17 15:21 UTC
To reproduce: I compiled with Python 3.7

https://mybinder.org/v2/gh/ornladios/ADIOS2-Jupyter.git/python-mpi
I get the following error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-abcec1771464> in <module>
----> 1 from mpi4py import MPI
      2 import numpy as np
      3 import adios2
      4 
      5 

ModuleNotFoundError: No module named 'mpi4py'
```

Working version with Python 3.6:
https://mybinder.org/v2/gh/williamfgc/notebooks/master

**Comment by betatim** [comment] 2019-03-18 08:52
I think the problem is that your `environment.yaml` file should be called `environment.yml`.

**Comment by williamfgc** [comment] 2019-03-22 00:47
@betatim thanks for the reply. After making the change I now get a `500: Internal Server Error`
I added a python-nompi branch that works fine. 

Fails (with mpi):
https://mybinder.org/v2/gh/ornladios/ADIOS2-Jupyter.git/python-mpi

Works (without mpi):
https://mybinder.org/v2/gh/ornladios/ADIOS2-Jupyter.git/python-nompi

**Comment by betatim** [comment] 2019-03-22 06:33
The internal server error is because of https://github.com/jupyter/repo2docker/issues/626 which needs fixing. I think a workaround might be to explicitly specify `notebook>5.7.4` in your dependencies.

**Comment by betatim** [comment] 2019-03-30 07:14
Closing now as https://github.com/jupyter/repo2docker/issues/626 has been fixed and deployed.

**Closed by betatim** 2019-03-30 07:14 UTC

**Comment by williamfgc** [comment] 2019-03-30 12:43
@betatim great, thanks!
