### ISSUE TITLE
Write up a post about the Orsay Binder on OpenStack deployment

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#506] opened 2018-03-28 15:06 UTC
At a recent meeting @minrk and I worked with @gouarin @nthiery and a bunch of others (please cc their github handles if anybody knows them) to deploy JupyterHub/BinderHub on OpenStack. We ran into several issues and made several workarounds for this.

I think it'd be great if we could write up this experience in a short blog post. I believe all of our scripts are here: https://plmlab.math.cnrs.fr/jupytercloud/kubernetes so perhaps this just means adding some context to them as well as a bit of narrative to help users make their way through the code (as well as a section on the particular issues we faced)

I think this could be a great way to provide a path forward for those who wish to deploy on OpenStack, and would also be a nice artifact to come out of our meeting.

**Comment by arnim** [comment] 2018-03-29 11:57
There is also the kubernetes bare metal deployment @bitnik is working on

**Comment by arnim** [comment] 2018-03-30 11:02
@choldgraf: As part of the DFG project [iLCM](https://www.gesis.org/en/research/external-funding-projects/overview-external-funding-projects/a-virtual-research-infrastructure-for-large-scale-qualitative-data/) @bitnik is currently setting up http://notebooks.gesis.org/ . 
We have already asked @betatim to let us know when a european meetup (maybe in Zurich) will take place to learn more about bh. 
Our project is in the very early stages but we aim in the longer term to work on enabling named-servers jupyterhub/jupyterhub#1409 with persistent storage #377 for authenticated users #323 . Our institute is dedicated to open source and work will be committed back as fare as possible.

**Comment by nthiery** [comment] 2018-03-30 18:37
For whatever it's worth, you may be interested by this blog post; kind of a personal wish list for our instance:
http://opendreamkit.org/2018/03/15/jupyterhub-binder-convergence/

**Comment by arnim** [comment] 2018-04-01 14:05
@nthiery thank you.

**Comment by bitnik** [comment] 2018-04-04 13:12
@choldgraf the github repo is currently piravate. Because there are some data specific to our institute. But very soon we want to separate it and have a public one. 

as @arnim mentioned, the website is https://notebooks.gesis.org/. There we have running [JupyterHub](https://notebooks.gesis.org/jupyter/) and [BinderHub](https://notebooks.gesis.org/binder/) separately.

**Comment by bitnik** [comment] 2018-04-11 09:24
@choldgraf we made the github repo of GESIS Notebooks public: https://github.com/gesiscss/orc

**Comment by gouarin** [comment] 2018-09-04 08:57
@psychemedia not for now but the work is almost done. 

We plan to write a blog post on Medium soon which will explain how to install jupyterhub using Kubernetes on OpenStack.

An other post will follow for binderhub installation.

**Comment by psychemedia** [comment] 2018-09-04 09:17
@gouarin Thanks - looking forward to giving it a try...

**Comment by choldgraf** [comment] 2018-09-18 18:50
@gouarin have you been in touch at all with people at Compute Canada? They've got a Kubernetes-on-openstack deployment of JupyterHub running as well. I can try to hunt down the URL to their configuration if it'd be helpful

**Comment by gouarin** [comment] 2018-09-28 13:54
@choldgraf sorry for the delay.

We worked hard on that this week and we finally solved our issues with the MTU. So now, we have a jupyterhub and a binderhub up and running (we tried to deploy both).

I saw what they did at Compute Canada and it's really nice. Our goal is nevertheless different. We don't want to develop our own ansible and terraform scripts to deploy binderhub because we will not have time to maintain them. So the idea is to use community tools like kubespray and it works pretty well.

I can now write the blog post and we'll see if it's reproducible ;).

**Comment by psychemedia** [comment] 2018-09-28 14:14
@gouarin I'm interested to see any guidance you have to see if I can get things to work with it...

**Comment by gouarin** [comment] 2018-10-15 13:56
@psychemedia done!

https://blog.jupyter.org/how-to-deploy-jupyterhub-with-kubernetes-on-openstack-f8f6120d4b1

**Comment by choldgraf** [comment] 2018-10-15 14:50
Wahoo! Way to @gouarin and team, thanks for sharing your experiences :-)

I think that before closing this issue, we should add a link to this blog in the [known binderhub deployments](https://binderhub.readthedocs.io/en/latest/known-deployments.html) page!

**Comment by psychemedia** [comment] 2018-10-16 14:28
@gouarin Great - thanks... will give it a go...

**Comment by manics** [comment] 2021-09-20 18:47
Closing as this is quite old now

**Closed by manics** 2021-09-20 18:47 UTC
Labels: collaborations
